#!/usr/bin/env bash
set -euo pipefail

ALERTMANAGER_URL=${ALERTMANAGER_URL:-http://localhost:9093}
ALERT_NAME=${ALERT_NAME:-PokecardSyntheticTestAlert}

START_END=$(node -e "const now=new Date(); const end=new Date(now.getTime()+10*60*1000); process.stdout.write(JSON.stringify({start:now.toISOString(),end:end.toISOString()}));")
START_AT=$(printf '%s' "$START_END" | sed -E 's#.*"start":"([^"]+)".*#\1#')
END_AT=$(printf '%s' "$START_END" | sed -E 's#.*"end":"([^"]+)".*#\1#')

PAYLOAD=$(cat <<JSON
[
  {
    "labels": {
      "alertname": "${ALERT_NAME}",
      "severity": "warning",
      "service": "pokecard-api"
    },
    "annotations": {
      "summary": "Synthetic observability test alert",
      "description": "This alert is generated by scripts/observability-fire-test-alert.sh"
    },
    "startsAt": "${START_AT}",
    "endsAt": "${END_AT}",
    "generatorURL": "http://localhost/test"
  }
]
JSON
)

curl -fsS \
  -X POST \
  -H 'Content-Type: application/json' \
  --data "$PAYLOAD" \
  "${ALERTMANAGER_URL}/api/v2/alerts" >/dev/null

sleep 2

curl -fsS "${ALERTMANAGER_URL}/api/v2/alerts" | tr -d '\n' | grep -q "\"alertname\":\"${ALERT_NAME}\""

printf 'Synthetic alert submitted and visible in Alertmanager: %s\n' "$ALERT_NAME"
